// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxvgohomcsuudrleepmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dmdvaG9tY3N1dWRybGVlcG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwOTQ1OTIsImV4cCI6MjA2NTY3MDU5Mn0.I7kvxG_yw_5iOzV3StJKr9aHBrEhWZtYjTT0ZDJnvHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);